BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `time` (
	`id`	INTEGER NOT NULL,
	`task_id`	INTEGER NOT NULL,
	`time`	TEXT NOT NULL,
	PRIMARY KEY(`id`)
);
CREATE TABLE IF NOT EXISTS `task` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`name`	TEXT NOT NULL,
	`date`	TEXT NOT NULL
);
COMMIT;
